### ISSUE TITLE
10 years from *when*?

### ISSUE THREAD

**Issue by gkop** [holman/extended-exercise-windows#24]
10 years is becoming somewhat of popular number, but I'm curious if in any cases it's a full 10 years _from leaving a company_. That is, I have seen in the wild an options grant agreement that indeed specified 10 years from leaving the company _but_ the agreement itself expires after 10 years.

Therefore, you can vest all your shares, for example in 4 years, and then leave the company. But under this agreement you apparently have only 6 years then to exercise.

I suspect the 10 year figure comes from [the statute on ISOs](https://www.law.cornell.edu/uscode/text/26/422), which says the options must be exercisable only within 10 years from the options grant. (I have no idea if this rule allows the ISOs to turn into NSOs like the rule about 3 months from leaving the company does)

Anyhow, I think it's important to get to the bottom of this, because a common understanding of the extended exercise window issue is, instead of getting the common 3 months [from leaving] to exercise, with an extended exercise window you get as long as 10 years, when that may not really ever be true (with a 1 year cliff, you'd only actually get max 9 years from leaving).

**Comment by holman** [comment]
> 10 years is becoming somewhat of popular number, but I'm curious if in any cases it's a full 10 years from leaving a company.

I think I've possibly heard of one or two companies doing this, but I think it's fairly rare.

> I suspect the 10 year figure comes from the statute on ISOs, which says the options must be exercisable only within 10 years from the options grant. (I have no idea if this rule allows the ISOs to turn into NSOs like the rule about 3 months from leaving the company does)

I'm not sure if NSOs can be > 10 years; if so, I imagine that once you convert into NSO from an ISO you won't be tied to anything related to the ISO anymore (since you don't have them anymore). So you'd be able to keep the NSOs for a much longer period (again, if that's actually allowed).

> Anyhow, I think it's important to get to the bottom of this, because a common understanding of the extended exercise window issue is, instead of getting the common 3 months [from leaving] to exercise, with an extended exercise window you get as long as 10 years, when that may not really ever be true (with a 1 year cliff, you'd only actually get max 9 years from leaving).

Yeah. I think the majority of startup employees (maybe 60-80%) have no idea about exercise windows. Those who have read up on a little bit of it probably have a better idea that it's from date of grant, or at least know enough to start asking questions.

I think the bigger problem over the coming years might be people realizing that 10 years doesn't necessarily mean that you're in the clear. We're already seeing companies IPO towards the eight or nine year range (or more), and it's not too far-fetched to think that five years from now we'll have people clamoring for virtually unlimited exercise windows, once they realize that their extended window is closing.

Good points with all of this, though. I'm going to close this issue out — just because I get antsy with an open issue around :) — but happy to continue to discuss this further with you or anyone else in this thread, of course!

**Comment by gkop** [comment]
I did some more digging and found that for the agreement to be valid for more than 10 years from date of grant, that would be extremely unusual, and the shares would have to be NSOs from the onset.
